language: node_js
branches:
  only:
    - master
node_js:
  - "12"
install:
  - npm install -g serverless
  - npm install -g yarn
  - yarn install
script:
  - yarn run lint
  - yarn run test:coveralls
  - AWS_ACCESS_KEY_ID=$aws_access_key_id AWS_SECRET_ACCESS_KEY=$aws_secret_access_key sls deploy --stage prd
cache:
  directories:
    - node_modules