language: python
python:
  - 3.8
node_js:
  - 14
branches:
  only:
    - master
before_install:
  - python --version
  - pip install -U pip
install:
  - npm install -g serverless
  - npm install
  - pip install pipenv
script:
  - AWS_ACCESS_KEY_ID=$aws_access_key_id AWS_SECRET_ACCESS_KEY=$aws_secret_access_key sls deploy --stage v1
cache:
  directories:
    - node_modules