service: mymangalist
frameworkVersion: '2'
useDotenv: true

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements: # DO NOT REMOVE THIS, THIS HELP US TO AVOID PYTHON VERSION ERRORS
    pythonBin: python3

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  logRetentionInDays: 5
  deploymentBucket: my-serverless-bucket-deployment
  apiGateway:
    apiKeys:
      - name: ${opt:stage}-malaquias
        value: ${env:GATEWAY_X_API_KEY} # you can hide it in a serverless variable and must be unique
        description: My personal api key
    usagePlan:
      # quota:
        #limit: 5000
        #offset: 2
        #period: month
      throttle:
        rateLimit: 50
        burstLimit: 100
  tags:
    project: ${self:service}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
            - cloudwatch:*
            - dynamodb:*
          Resource: "*"
  environment:
    DYNAMODB_MANGAS_TABLE_NAME: ${self:service}_${self:provider.stage}_mangas

package:
  individually: true

functions:
  - ${file(src/functions/createNewManga/function.yml)}
  - ${file(src/functions/listMyMangas/function.yml)}
  - ${file(src/functions/listMyMangasScores/function.yml)}
  - ${file(src/functions/addNewScore/function.yml)}

resources:
  - ${file(resources/api-gateway.yml)}
