Resources:
  MangaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:provider.environment.DYNAMODB_MANGAS_TABLE_NAME}
      AttributeDefinitions:
        - AttributeName: title
          AttributeType: S
        KeySchema:
        - AttributeName: title
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0
      GlobalSecondaryIndexes:
        - IndexName: status
            KeySchema:
                - AttributeName: status
                  KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 0
              WriteCapacityUnits: 0
        - IndexName: mangaStatus
          KeySchema:
            - AttributeName: mangaStatus
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 0
            WriteCapacityUnits: 0